Added mapping of job to GPU ID and locking of map file

diff --git a/libexec/common b/libexec/common
--- a/libexec/common
+++ b/libexec/common
@@ -8,33 +8,60 @@ logging (){
  echo "$hostname $timestamp $1" >> /var/log/dgx-cgroup
 }
 
+write_gpu_assignment(){
+ echo unset gpu_status gpu_cgroup gpu_user > "$map_gpu"
+ echo declare -a gpu_status gpu_cgroup gpu_user >> "$map_gpu"
+ echo gpu_status=\(${gpu_status[*]}\) >> "$map_gpu"
+ echo gpu_cgroup=\(${gpu_cgroup[*]}\) >> "$map_gpu"
+ echo gpu_user=\(${gpu_user[*]}\) >> "$map_gpu"
+}
+
+reset_gpu_assignment(){
+ unset gpu_status gpu_cgroup gpu_user
+ declare -a gpu_status gpu_cgroup gpu_user
+ for i in {0..7} ; do gpu_status[$i]=A ; gpu_cgroup[$i]=NA ; gpu_user[$i]=NA ; done
+ write_gpu_assignment
+}
+
 if [ ! -d "$rundir" ] ; then mkdir "$rundir" || { logging "cgroup error creating $rundir" ; exit 1 ; } ; fi
-if [ ! -f "$map_gpu" ] ; then
-cat << EOF > "$map_gpu"
-#ID STATUS JOB
-0,A,NA
-1,A,NA
-2,A,NA
-3,A,NA
-4,A,NA
-5,A,NA
-6,A,NA
-7,A,NA
-EOF
-fi
 
 assign_gpus(){
-if [ $# -ne 2 ] ; then { logging "cgroup error assign GPU arguments $@"  ; exit 1 ; } ; fi
+if [ $# -ne 3 ] ; then { logging "cgroup error assign GPU arguments $@"  ; exit 1 ; } ; fi
 _cgroup="$1"
 _ngpus="$2"
-_i=`expr $_ngpus - 1`
-echo `seq 0 $_i`
+_user="$3"
+_required="$_ngpus"
+_gpus=""
+if [ ! -f "$map_gpu" ] ; then reset_gpu_assignment ; fi
+source "$map_gpu"
+for i in {0..7} ; do
+ if [ $_required -eq 0 ] ; then break ; fi
+ if [ "${gpu_status[$i]}" == A ] ; then
+  gpu_status[$i]="B"
+  gpu_cgroup[$i]="$_cgroup"
+  gpu_user[$i]="$_user"
+  _gpus="$_gpus $i"
+  _required=`expr $_required - 1`
+ fi
+done
+if [ $_required -gt 0 ] ; then { logging "cgroup error assign could not find enough GPUs"  ; exit 1 ; } ; fi
+write_gpu_assignment
+echo $_gpus
 }
 
 release_gpus(){
-for g in "$@" ; do
- echo sed -i 's/^${g},.*/^${g},A,NA/' $map_gpu
+if [ $# -ne 1 ] ; then { logging "cgroup error release GPU arguments $@"  ; exit 1 ; } ; fi
+_cgroup="$1"
+if [ ! -f "$map_gpu" ] ; then { logging "cgroup error release no map file" ; exit 1 ; } ; fi
+source "$map_gpu"
+for i in {0..7} ; do
+ if [ "${gpu_cgroup[$i]}" == "$_cgroup" ] ; then
+  gpu_status[$i]="A"
+  gpu_cgroup[$i]="NA"
+  gpu_user[$i]="NA"
+ fi
 done
+write_gpu_assignment
 }
 
 cgroup_create(){
@@ -68,6 +95,7 @@ cgroup_remove(){
  if [ $# -ne 1 ] ; then { logging "cgroup remove error arguments $@"  ; return 1 ; } ; fi
  _cgroup="$1"
  for _g in allgpu nogpu ; do if [ x"$_cgroup" == x"$_g" ] ; then { logging "cgroup skipping delete $_g"  ; return 0 ; } ; fi  ; done
+ release_gpus "$_cgroup"
  nogpu=nogpu
  if [ ! -d /sys/fs/cgroup/devices/$nogpu ] ; then
   cgcreate -g "devices:/$nogpu" --tperm 0666 || { logging "cgroup error cgcreate ${nogpu}" ; return 1 ; }
